name: Run Bot and Flask Continuously

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run_bot:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev build-essential libsndfile1

      - name: Setup virtual environment and install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Corrigi para "requirements.txt", supondo que esse seja o nome correto

      - name: Run Flask and Bot
        run: |
          nohup python app.py &
        continue-on-error: true
