name: Run Bot and Flask Continuously

on:
  schedule:
    - cron: '*/5 * * * *'  # Executa a cada 5 minutos. Pode ajustar conforme necessário.
  workflow_dispatch:  # Permite acionar manualmente o workflow a partir do GitHub.

jobs:
  run_bot:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requests.txt
          sudo apt-get update
          sudo apt-get install -y python3-dev build-essential

      - name: Run Flask and Bot
        run: |
          nohup python app.py &  # Executa o bot e o Flask em segundo plano
        continue-on-error: true  # Garante que o workflow não falhe se houver erros
