name: Run Discord Bot

on:
  push:
    branches:
      - master  # ou main, dependendo de qual branch é o principal
  pull_request:
    branches:
      - master  # ou main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # ou a versão que você está usando

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requests.txt  # Certifique-se de ter esse arquivo no repositório

    - name: Run bot
      run: |
        python app.py  # ou o nome do arquivo principal do seu bot
