name: Run Bot and Flask Continuously

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run_bot:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requests.txt
          source venv/bin/activate
          sudo apt-get update
          sudo apt-get install -y python3-dev build-essential
          python3 -m venv venv
          source venv/bin/activate
          
         
        - name: Install system dependencies
         run: |
           sudo apt-get update && sudo apt-get install -y libsndfile1
          
          
      - name: Run Flask and Bpython3ot
        run: |
          nohup python app.py &
        continue-on-error: true
