name: Run Bot and Flask Continuously

on:
  schedule:
    - cron: '*/5 * * * *'  # Executa a cada 5 minutos
  workflow_dispatch:  # Também pode ser disparado manualmente

jobs:
  run_bot:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Add universe repository
        run: |
          sudo add-apt-repository universe
          sudo apt-get update

      - name: Check if libopenjp2-7-dev is available
        run: |
          apt-cache search libopenjp2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          pkg-config valgrind emacs-nox libltdl-dev libtiff-tools exiftool git git-lfs cmake \
          liblcms2-dev libtiff-dev libpng-dev libheif-dev libz-dev unzip libzstd-dev libwebp-dev \
          build-essential hwinfo python3-jpylyzer libfreetype6-dev liblcms2-dev libopenjp2-7-dev \
          libopenjp2-tools libwebp-dev libsndfile1 libjpeg-dev zlib1g-dev

      - name: Install OpenJPEG
        run: |
          wget https://github.com/uclouvain/openjpeg/archive/master.zip
          unzip master.zip
          cd openjpeg-master
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make -j$(nproc)
          sudo make install
          cd ~
          rm -rf openjpeg-master master.zip

      - name: Install ImageMagick
        run: |
          wget https://github.com/ImageMagick/ImageMagick/archive/refs/heads/main.zip
          unzip main.zip
          cd ImageMagick-main
          sudo apt-get install -y libgrokj2k1 grokj2k-tools libgrokj2k1-dev libgrokj2k1-doc
          cd ~
          rm -rf ImageMagick-main main.zip

      - name: Install Python dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install pillow[openjpeg]
          pip install -r requirements.txt

      - name: Run Flask and Bot
        run: |
          source venv/bin/activate
          nohup python app.py &
        continue-on-error: true
