name: Run Bot and Flask Continuously

on:
  schedule:
    - cron: '*/5 * * * *'  # Executa a cada 5 minutos
  workflow_dispatch:  # Também pode ser disparado manualmente

jobs:
  run_bot:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv venv  # Cria o ambiente virtual
          source venv/bin/activate  # Ativa o ambiente virtual
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Instala dependências

      - name: Install system dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y libsndfile1

      - name: Run Flask and Bot
        run: |
          source venv/bin/activate  # Ativa novamente o ambiente virtual
          nohup python app.py &  # Executa o bot e o Flask em segundo plano
        continue-on-error: true
